# Introduction to Pandas and NumPy

## --> Pandas (stands for Python Data Analysis) is an open-source software library designed for data manipulation and analysis.

### ->Built on top of NumPy, efficiently manages large datasets, offering tools for data cleaning, transformation and analysis.
### ->Seamlessly integrates with other Python libraries like NumPy, Matplotlib and scikit-learn.
### ->Revolves around two primary Data structures: Series (1D) and DataFrame (2D)
### ->Provides methods like .dropna() and .fillna() to handle missing values seamlessly

## -->What is Pandas Used for?

### ->Reading and writing data from various file formats like CSV, Excel and SQL databases.
### ->Cleaning and preparing data (handling missing values, filtering, removing duplicates).
### ->Merging, joining, and reshaping datasets.
### ->Performing statistical analysis and descriptive statistics.
### ->Visualizing data quickly.

## 1 Creating a dataframe from an array

### 1.1 Option 1

In [2]:
import numpy as np
import pandas as pd

In [3]:
# creating an array
data = np.array([[1,2],[2,5],[3,6]])

In [4]:
# Creating dataframe
pd.DataFrame(data)

   0  1
0  1  2
1  2  5
2  3  6

In [5]:
# Creating dataframe
df = pd.DataFrame(data,index=['row1','row2','row3'],
                 columns = ['col1','col2'])

In [6]:
# showing the dataFrame
df

      col1  col2
row1     1     2
row2     2     5
row3     3     6

### 1.2 option 2

In [7]:
data = [[1,2],[2,5],[3,6]]

In [8]:
# Creating dataframe
df = pd.DataFrame(data,index=['row1','row2','row3'],
                 columns = ['col1','col2'])

In [9]:
# showing the dataFrame
df

      col1  col2
row1     1     2
row2     2     5
row3     3     6

## 2 Creating a DataFrame from a dictionary

In [10]:
city = ['Ahmedabad', 'Patan', 'Mehsana', 'Gandhinagar']
population = [345635,356748,567345,678935]

In [11]:
# storing lists within a dictionary
dict_state = {'City': city , 'Population':population}

In [12]:
# Creating dataframe
df_population = pd.DataFrame(dict_state)

In [13]:
# showing the dataFrame
df_population

          City  Population
0    Ahmedabad      345635
1        Patan      356748
2      Mehsana      567345
3  Gandhinagar      678935

## 3 Creating a DataFrame from a csv file

In [14]:
# reading the csv file
df_exam =pd.read_csv('StudentsPerformance.csv')

In [15]:
# show first 5 rows in a dataframe
df_exam.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [16]:
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [17]:
# show  last  5 rows in dataframe
df_exam.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [18]:
# show n rows in dataframe
df_exam.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [19]:
df_exam.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [20]:
df_exam.shape

(1000, 8)

In [21]:
df_exam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [22]:
# display n rows

In [23]:
# pd.set_option('display.max_rows', 1000)
# df_exam

## 4 Attributes

In [24]:
# getting access to shape attribute
df_exam.shape

(1000, 8)

In [25]:
# getting access of index attribute
df_exam.index

RangeIndex(start=0, stop=1000, step=1)

In [26]:
# getting access of columns attribuite
df_exam.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [27]:
df_exam.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

## 6 Methods

In [28]:
df_exam.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [29]:
df_exam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [30]:
df_exam.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## 7 Function

In [31]:
len(df_exam)

1000

In [32]:
max(df_exam)

'writing score'

In [33]:
max(df_exam.index)

999

In [34]:
min(df_exam)

'gender'

In [35]:
type(df_exam)

pandas.core.frame.DataFrame

## 8 Selecting One Column

### 8.1 Syntax 1

In [36]:
df_exam['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [37]:
df_exam['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

### 8.2 Syntax 2

In [38]:
df_exam.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [39]:
#df_exam.math score # SyntaxError: invalid syntax
df_exam['math score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

## 9 Selecting two or more columns

In [40]:
df_exam[['gender','math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [41]:
df_exam[['gender','math score','reading score', 'writing score']]

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

## 10 Adding new Column

### 10.1 Adding a new column with a scalar value

In [42]:
df_exam['language score'] = 70

In [43]:
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

### 10.2 Adding a new column with an array

In [44]:
# create random integer bnumber b/n 1-100
int_language_score =np.random.randint(1,100,size=1000)

In [45]:
min(int_language_score)
max(int_language_score)

np.int32(99)

In [46]:
df_exam['language score'] = int_language_score
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,64
1,female,group C,some college,standard,completed,69,90,88,99
2,female,group B,master's degree,standard,none,90,95,93,17
3,male,group A,associate's degree,free/reduced,none,47,57,44,25
4,male,group C,some college,standard,none,76,78,75,23
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,22
996,male,group C,high school,free/reduced,none,62,55,55,22
997,female,group C,high school,free/reduced,completed,59,71,65,71
998,female,group D,some college,standard,completed,68,78,77,2
999,female,group D,some college,free/reduced,none,77,86,86,76

In [47]:
# create random float number b/n 1-100
np.random.uniform(1,100,size=100)

array([57.32977905,  8.69232581, 16.7959835 , 26.149979  , 24.03586178,
       29.18474634, 66.58432036, 75.2913755 , 55.46546076, 91.27965334,
       32.42482132, 44.90764034, 37.66764891,  2.23674383,  6.03921687,
       10.23902588, 84.74449589, 37.62332645, 72.49555893, 70.82688843,
       79.92149524, 14.87064848, 12.53238662, 29.19667386,  6.8159652 ,
       80.76041118,  7.70635144, 22.35472954, 43.91076719, 85.33720087,
       80.63582079, 42.38823654, 54.65309176, 95.0338659 , 34.50484948,
       79.91872014, 45.34430017, 94.83987667, 15.98411312, 76.73332631,
       16.03912769, 10.41182532, 72.57942791, 38.89526833, 49.36198081,
       65.4674322 , 57.52422049, 91.71694764, 79.51709777, 75.05591968,
       70.0475133 , 53.69894107, 93.91584505, 27.69054789, 18.5527731 ,
       18.60030424, 93.12343837, 67.7465394 , 25.87070657, 68.13146457,
       14.90498903, 69.20170781, 61.26898646, 87.45600214, 61.72057169,
       70.6540825 , 25.36701323,  6.01751351, 39.25967017, 65.84657103,
       54.11299273, 33.01085249, 16.79677659, 91.72661812, 57.04341741,
       65.18718952, 41.30455341, 18.32050254, 85.42777282,  4.41728594,
        6.41607715, 59.00898348, 82.11030749, 27.25418086, 37.02370322,
       44.33139195, 41.59666762, 77.23055425, 30.4245567 , 75.40306888,
       44.97006036, 11.71458112, 27.35882566, 66.72930484, 42.0646213 ,
       28.67756447, 70.00266713, 31.38600159, 45.51384894, 32.77962124])

### 10.3 assign()

When to use assign?
 * Add multiple columns in a single line of code
 * when you need to overwrite the value of an eexiting columns


it return a new object(a copy) with all the original columns in addition to the new ones

In [48]:
# create random number for our new score columns
score1 = np.random.randint(1,100,size=1000)
score2 = np.random.randint(1,100,size=1000)

In [49]:
# create a series using the random number 
series1=pd.Series(score1,index=np.arange(0,1000))
series2=pd.Series(score2,index=np.arange(0,1000))

In [50]:
series1

0      47
1      34
2      99
3      59
4       6
       ..
995    54
996    49
997    63
998    53
999    86
Length: 1000, dtype: int32

In [51]:
series2

0       9
1      18
2       1
3       1
4      52
       ..
995    50
996    15
997     6
998     4
999    98
Length: 1000, dtype: int32

In [52]:
df_exam.assign(score1=series1,score2=series2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,64,47,9
1,female,group C,some college,standard,completed,69,90,88,99,34,18
2,female,group B,master's degree,standard,none,90,95,93,17,99,1
3,male,group A,associate's degree,free/reduced,none,47,57,44,25,59,1
4,male,group C,some college,standard,none,76,78,75,23,6,52
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,22,54,50
996,male,group C,high school,free/reduced,none,62,55,55,22,49,15
997,female,group C,high school,free/reduced,completed,59,71,65,71,63,6
998,female,group D,some college,standard,completed,68,78,77,2,53,4
999,female,group D,some college,free/reduced,none,77,86,86,76,86,98

In [53]:
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,64
1,female,group C,some college,standard,completed,69,90,88,99
2,female,group B,master's degree,standard,none,90,95,93,17
3,male,group A,associate's degree,free/reduced,none,47,57,44,25
4,male,group C,some college,standard,none,76,78,75,23
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,22
996,male,group C,high school,free/reduced,none,62,55,55,22
997,female,group C,high school,free/reduced,completed,59,71,65,71
998,female,group D,some college,standard,completed,68,78,77,2
999,female,group D,some college,free/reduced,none,77,86,86,76

In [54]:
df_exam=df_exam.assign(score1=series1,score2=series2)
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,64,47,9
1,female,group C,some college,standard,completed,69,90,88,99,34,18
2,female,group B,master's degree,standard,none,90,95,93,17,99,1
3,male,group A,associate's degree,free/reduced,none,47,57,44,25,59,1
4,male,group C,some college,standard,none,76,78,75,23,6,52
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,22,54,50
996,male,group C,high school,free/reduced,none,62,55,55,22,49,15
997,female,group C,high school,free/reduced,completed,59,71,65,71,63,6
998,female,group D,some college,standard,completed,68,78,77,2,53,4
999,female,group D,some college,free/reduced,none,77,86,86,76,86,98

### 10.4 insert()

In [55]:
df_exam.insert(1,'test' , series1)

In [56]:
df_exam

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,47,group B,bachelor's degree,standard,none,72,72,74,64,47,9
1,female,34,group C,some college,standard,completed,69,90,88,99,34,18
2,female,99,group B,master's degree,standard,none,90,95,93,17,99,1
3,male,59,group A,associate's degree,free/reduced,none,47,57,44,25,59,1
4,male,6,group C,some college,standard,none,76,78,75,23,6,52
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,54,group E,master's degree,standard,completed,88,99,95,22,54,50
996,male,49,group C,high school,free/reduced,none,62,55,55,22,49,15
997,female,63,group C,high school,free/reduced,completed,59,71,65,71,63,6
998,female,53,group D,some college,standard,completed,68,78,77,2,53,4
999,female,86,group D,some college,free/reduced,none,77,86,86,76,86,98

## 11 Operations on Dataframe

### 1 Math Operation

### 1.1 Operation in column

In [57]:
# select a column and calculate total sum
df_exam['math score'].sum()

np.int64(66089)

In [58]:
# count ,mean,std,max,min
print(df_exam['math score'].count())
print(df_exam['math score'].mean())
print(df_exam['math score'].std())
print(df_exam['math score'].max())
print(df_exam['math score'].min())

1000
66.089
15.163080096009468
100
0

In [59]:
# easier calculation with .describe()
df_exam.describe()

,test,math score,reading score,writing score,language score,score1,score2
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000
mean,48.705000,66.08900,69.169000,68.054000,49.52200,48.705000,51.177000
std,28.340522,15.16308,14.600192,15.195657,29.09715,28.340522,29.026854
min,1.000000,0.00000,17.000000,10.000000,1.00000,1.000000,1.000000
25%,24.000000,57.00000,59.000000,57.750000,23.00000,24.000000,26.000000
50%,49.000000,66.00000,70.000000,69.000000,49.00000,49.000000,52.000000
75%,73.000000,77.00000,79.000000,79.000000,74.00000,73.000000,77.000000
max,99.000000,100.00000,100.000000,100.000000,99.00000,99.000000,99.000000

###  1.2 Operation in rows

In [60]:
# calculating the sum in a row
df_exam['math score']+df_exam['reading score']+df_exam['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [61]:
# calculation the average and assigning the result to a new column
df_exam['average']=(df_exam['math score']+df_exam['reading score']+df_exam['writing score'])/3

In [62]:
df_exam

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
0,female,47,group B,bachelor's degree,standard,none,72,72,74,64,47,9,72.666667
1,female,34,group C,some college,standard,completed,69,90,88,99,34,18,82.333333
2,female,99,group B,master's degree,standard,none,90,95,93,17,99,1,92.666667
3,male,59,group A,associate's degree,free/reduced,none,47,57,44,25,59,1,49.333333
4,male,6,group C,some college,standard,none,76,78,75,23,6,52,76.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,54,group E,master's degree,standard,completed,88,99,95,22,54,50,94.000000
996,male,49,group C,high school,free/reduced,none,62,55,55,22,49,15,57.333333
997,female,63,group C,high school,free/reduced,completed,59,71,65,71,63,6,65.000000
998,female,53,group D,some college,standard,completed,68,78,77,2,53,4,74.333333
999,female,86,group D,some college,free/reduced,none,77,86,86,76,86,98,83.000000

In [63]:
df_exam.round(2)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
0,female,47,group B,bachelor's degree,standard,none,72,72,74,64,47,9,72.67
1,female,34,group C,some college,standard,completed,69,90,88,99,34,18,82.33
2,female,99,group B,master's degree,standard,none,90,95,93,17,99,1,92.67
3,male,59,group A,associate's degree,free/reduced,none,47,57,44,25,59,1,49.33
4,male,6,group C,some college,standard,none,76,78,75,23,6,52,76.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,54,group E,master's degree,standard,completed,88,99,95,22,54,50,94.00
996,male,49,group C,high school,free/reduced,none,62,55,55,22,49,15,57.33
997,female,63,group C,high school,free/reduced,completed,59,71,65,71,63,6,65.00
998,female,53,group D,some college,standard,completed,68,78,77,2,53,4,74.33
999,female,86,group D,some college,free/reduced,none,77,86,86,76,86,98,83.00

## 12 Value Counts

In [64]:
# counting gender element by category
df_exam['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [65]:
# return relative frequency
df_exam['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [66]:
df_exam['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [67]:
df_exam['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

## 13 Sort dataframe

In [68]:
df_exam.sort_values('math score')

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
59,female,97,group C,some high school,free/reduced,none,0,17,10,51,97,99,9.000000
980,female,5,group B,high school,free/reduced,none,8,24,23,47,5,32,18.333333
17,female,84,group B,some high school,free/reduced,none,18,32,28,27,84,14,26.000000
787,female,47,group B,some college,standard,none,19,38,32,13,47,16,29.666667
145,female,51,group C,some college,free/reduced,none,22,39,33,59,51,22,31.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,male,51,group D,some college,standard,completed,100,97,99,77,51,22,98.666667
623,male,51,group A,some college,standard,completed,100,96,86,66,51,25,94.000000
451,female,69,group E,some college,standard,none,100,92,97,81,69,77,96.333333
962,female,84,group E,associate's degree,standard,none,100,100,100,42,84,62,100.000000
149,male,74,group E,associate's degree,free/reduced,completed,100,100,93,26,74,81,97.666667

In [69]:
df_exam.sort_values('math score', ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
962,female,84,group E,associate's degree,standard,none,100,100,100,42,84,62,100.000000
625,male,51,group D,some college,standard,completed,100,97,99,77,51,22,98.666667
458,female,67,group E,bachelor's degree,standard,none,100,100,100,62,67,7,100.000000
623,male,51,group A,some college,standard,completed,100,96,86,66,51,25,94.000000
451,female,69,group E,some college,standard,none,100,92,97,81,69,77,96.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,51,group C,some college,free/reduced,none,22,39,33,59,51,22,31.333333
787,female,47,group B,some college,standard,none,19,38,32,13,47,16,29.666667
17,female,84,group B,some high school,free/reduced,none,18,32,28,27,84,14,26.000000
980,female,5,group B,high school,free/reduced,none,8,24,23,47,5,32,18.333333
59,female,97,group C,some high school,free/reduced,none,0,17,10,51,97,99,9.000000

In [70]:
df_exam.sort_values(['math score','reading score']) 
# its only make copy dont upgrade data frame
# for update use inplace=True

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
59,female,97,group C,some high school,free/reduced,none,0,17,10,51,97,99,9.000000
980,female,5,group B,high school,free/reduced,none,8,24,23,47,5,32,18.333333
17,female,84,group B,some high school,free/reduced,none,18,32,28,27,84,14,26.000000
787,female,47,group B,some college,standard,none,19,38,32,13,47,16,29.666667
145,female,51,group C,some college,free/reduced,none,22,39,33,59,51,22,31.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,male,51,group D,some college,standard,completed,100,97,99,77,51,22,98.666667
149,male,74,group E,associate's degree,free/reduced,completed,100,100,93,26,74,81,97.666667
458,female,67,group E,bachelor's degree,standard,none,100,100,100,62,67,7,100.000000
916,male,89,group E,bachelor's degree,standard,completed,100,100,100,19,89,51,100.000000
962,female,84,group E,associate's degree,standard,none,100,100,100,42,84,62,100.000000

In [71]:
df_exam.sort_values('race/ethnicity')

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
778,female,22,group A,some college,standard,completed,72,79,82,46,22,35,77.666667
546,female,57,group A,some high school,standard,completed,92,100,97,11,57,50,96.333333
820,female,85,group A,some high school,standard,completed,85,90,92,84,85,87,89.000000
741,female,45,group A,associate's degree,free/reduced,none,37,57,56,83,45,96,50.000000
305,male,53,group A,some college,standard,none,69,67,69,85,53,58,68.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,male,46,group E,associate's degree,standard,completed,71,74,68,78,46,71,71.000000
293,female,21,group E,bachelor's degree,standard,none,65,73,75,41,21,82,71.000000
289,male,87,group E,some high school,standard,completed,77,76,77,48,87,52,76.666667
206,male,60,group E,bachelor's degree,standard,none,82,62,62,88,60,83,68.666667
499,male,59,group E,some college,standard,none,76,71,72,64,59,68,73.000000

## 14 Create Index

In [72]:
import random

In [73]:
new_index = np.arange(0,1000)

In [74]:
random.shuffle(new_index)

In [75]:
df_exam['new_index']=new_index

In [76]:
df_exam

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average,new_index
0,female,47,group B,bachelor's degree,standard,none,72,72,74,64,47,9,72.666667,379
1,female,34,group C,some college,standard,completed,69,90,88,99,34,18,82.333333,562
2,female,99,group B,master's degree,standard,none,90,95,93,17,99,1,92.666667,604
3,male,59,group A,associate's degree,free/reduced,none,47,57,44,25,59,1,49.333333,352
4,male,6,group C,some college,standard,none,76,78,75,23,6,52,76.333333,484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,54,group E,master's degree,standard,completed,88,99,95,22,54,50,94.000000,511
996,male,49,group C,high school,free/reduced,none,62,55,55,22,49,15,57.333333,144
997,female,63,group C,high school,free/reduced,completed,59,71,65,71,63,6,65.000000,720
998,female,53,group D,some college,standard,completed,68,78,77,2,53,4,74.333333,769
999,female,86,group D,some college,free/reduced,none,77,86,86,76,86,98,83.000000,981

## 15 Set Index

In [77]:
df_exam.set_index('new_index', inplace=True)

In [78]:
df_exam

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
new_index,,,,,,,,,,,,,
379,female,47,group B,bachelor's degree,standard,none,72,72,74,64,47,9,72.666667
562,female,34,group C,some college,standard,completed,69,90,88,99,34,18,82.333333
604,female,99,group B,master's degree,standard,none,90,95,93,17,99,1,92.666667
352,male,59,group A,associate's degree,free/reduced,none,47,57,44,25,59,1,49.333333
484,male,6,group C,some college,standard,none,76,78,75,23,6,52,76.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,female,54,group E,master's degree,standard,completed,88,99,95,22,54,50,94.000000
144,male,49,group C,high school,free/reduced,none,62,55,55,22,49,15,57.333333
720,female,63,group C,high school,free/reduced,completed,59,71,65,71,63,6,65.000000
769,female,53,group D,some college,standard,completed,68,78,77,2,53,4,74.333333
981,female,86,group D,some college,free/reduced,none,77,86,86,76,86,98,83.000000

## 16 sort index

In [79]:
df_exam.sort_index()

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average
new_index,,,,,,,,,,,,,
0,female,83,group A,some high school,free/reduced,none,47,59,50,12,83,82,52.000000
1,female,37,group C,high school,standard,none,72,80,83,39,37,34,78.333333
2,male,77,group E,some high school,free/reduced,completed,73,67,59,75,77,51,66.333333
3,female,94,group C,some college,free/reduced,completed,63,73,71,2,94,33,69.000000
4,male,4,group B,some college,free/reduced,completed,74,77,76,16,4,74,75.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,male,82,group C,associate's degree,free/reduced,none,73,68,66,44,82,97,69.000000
996,male,93,group A,bachelor's degree,standard,none,66,64,62,80,93,69,64.000000
997,male,59,group E,some college,standard,none,76,71,72,64,59,68,73.000000
998,male,41,group B,high school,standard,completed,52,49,46,52,41,79,49.000000
999,male,91,group D,some college,standard,none,81,82,84,16,91,13,82.333333

In [80]:
df_exam =pd.read_csv('StudentsPerformance.csv')

In [81]:
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

## 1 Rename Column

In [82]:
df_exam=df_exam.rename(columns={'gender':'Gender'})

In [83]:
df_exam

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [84]:
df_exam.rename(columns={'math score':'MS',
                               'reading score':'RS',
                               'writing score': 'Ws'}, inplace=True)

In [85]:
df_exam.head(3)

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,Ws
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93

In [86]:
df_exam.rename(index={0:'A',1:'B',2:'C'},inplace=True)

In [87]:
df_exam.head(3)

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,Ws
A,female,group B,bachelor's degree,standard,none,72,72,74
B,female,group C,some college,standard,completed,69,90,88
C,female,group B,master's degree,standard,none,90,95,93