In [1]:
import pandas  as pd

### 1. Read a CSv from a URL with 
Target website: https://www.football-data.co.uk/data.php

In [3]:
# reading 1 csv file from the website
df_premier25 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2526/E0.csv")

In [ ]:
# showing dataframe
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

In [5]:
# rename columns
df_premier25.rename(columns={'FTHG':'home_goals',
                             'FTAG':'away_goals',},inplace=True)

In [6]:
# show dataframe
df_premier25.head(5)

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

### 2. Read csv from Multiple URLs with pandas
-https://www.football-data.co.uk/mmz4281/2526/E0.csv

-https://www.football-data.co.uk/mmz4281/2526/E1.csv

Link : root + season + league

In [7]:
# link structure 
"https://www.football-data.co.uk/mmz4281/" + "2526" + "/" + "E1" + ".csv"

'https://www.football-data.co.uk/mmz4281/2526/E1.csv'

In [9]:
# create a root variable
root = "https://www.football-data.co.uk/mmz4281/"

### 2.1 Multiple leagues

* https://www.football-data.co.uk/mmz4281/2526/E0.csv
* https://www.football-data.co.uk/mmz4281/2526/E1.csv
* https://www.football-data.co.uk/mmz4281/2526/E2.csv
* https://www.football-data.co.uk/mmz4281/2526/E3.csv
* https://www.football-data.co.uk/mmz4281/2526/Ec.csv

In [10]:
# creating list of leagues
leagues = [
    "E0",
    "E1",
    "E2",
    "E3",
    "Ec",
]

frames = []

# looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + "2526" + "/" + league + ".csv")
    frames.append(df)

In [11]:
# length of frames
len(frames)

5

In [14]:
# show 1st ,2nd and 3rd element
frames[0].head(5)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [15]:
frames[4].head(5)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12

### 2.2 Multiple seasons

In [17]:
for season in range(15,26):
    print(str(season)+str(season+1))

1516
1617
1718
1819
1920
2021
2122
2223
2324
2425
2526

In [20]:
leagues = [
    "E0",
    "E1",
    "E2",
    "E3",
    "Ec",
]

frames = []

# loops through range of season and insert new column
for league in leagues:
    for season in range(20, 26):
        df = pd.read_csv(root + str(season) + str(season + 1) + "/" + league + ".csv", encoding='unicode_escape')
        df.insert(1,"season",season)
        frames.append(df)

In [21]:
# total frames ( 6 season X 5 leagues)
len(frames)

30

In [24]:
# Show 1st season
frames[0].head(5)

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,20,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,20,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,20,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,20,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,20,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97

In [25]:
# show last season
frames[29].head(5)

,ï»¿Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,25,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,25,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,25,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,25,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,25,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12

### 3. Organize All the Data in dictionary

In [26]:
# create a dictionary with original name of league as key
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [28]:
# get a dictionaty element
dict_countries['Spanish La Liga']

'SP1'

In [29]:
for league in dict_countries:
    print(f"{league}:{dict_countries[league]}")

Spanish La Liga:SP1
Spanish Segunda Division:SP2
German Bundesliga:D1
English Premier League:E0
English League 1:E2
English League 2:E3

In [ ]:
dict_historical_data = {}


# looping through key elements 
# to get all season data of perticular league in one dataframe
for league in dict_countries:
    frames=[] # inside loop b's we need to clear older league data to assign new league data
    for season in range(20,26):
        df = pd.read_csv(root + str(season) + str(season + 1) + "/" + dict_countries[league] + ".csv", encoding='unicode_escape')
        df.insert(1,"season",season)
        frames.append(df)
    df_concat= pd.concat(frames)
    dict_historical_data[league] = df_concat

In [31]:
len(dict_historical_data)

6

In [33]:
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Segunda Division', 'German Bundesliga', 'English Premier League', 'English League 1', 'English League 2'])

In [ ]:
dict_historical_data['Spanish La Liga'].head(5)

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,SP1,20,12/09/2020,15:00,Eibar,Celta,0,0,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,20,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,20,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,20,13/09/2020,13:00,Alaves,Betis,0,1,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,20,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dict_historical_data['Spanish La Liga'].tail(5)

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
375,NaN,25,23/05/2026,20:00,Girona,Elche,1,1,D,0,...,3.95,1.75,3.80,4.40,1.80,3.8,4.20,1.80,3.75,4.20
376,NaN,25,23/05/2026,20:00,Mallorca,Oviedo,3,0,H,1,...,6.50,1.45,4.33,7.50,1.48,4.4,6.50,1.48,4.40,6.50
377,NaN,25,23/05/2026,20:00,Real Madrid,Ath Bilbao,4,2,H,2,...,5.20,1.53,4.60,5.50,1.55,4.8,5.00,1.55,4.60,5.00
378,NaN,25,23/05/2026,20:00,Valencia,Barcelona,3,1,H,0,...,1.87,3.40,4.10,1.93,3.40,4.0,1.95,3.30,4.00,1.95
379,NaN,25,24/05/2026,20:00,Villarreal,Ath Madrid,5,1,H,4,...,2.45,NaN,NaN,NaN,NaN,NaN,NaN,2.40,3.80,2.60

In [37]:
dict_historical_data['Spanish La Liga']

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,SP1,20,12/09/2020,15:00,Eibar,Celta,0,0,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,20,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,20,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,20,13/09/2020,13:00,Alaves,Betis,0,1,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,20,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,NaN,25,23/05/2026,20:00,Girona,Elche,1,1,D,0,...,3.95,1.75,3.80,4.40,1.80,3.8,4.20,1.80,3.75,4.20
376,NaN,25,23/05/2026,20:00,Mallorca,Oviedo,3,0,H,1,...,6.50,1.45,4.33,7.50,1.48,4.4,6.50,1.48,4.40,6.50
377,NaN,25,23/05/2026,20:00,Real Madrid,Ath Bilbao,4,2,H,2,...,5.20,1.53,4.60,5.50,1.55,4.8,5.00,1.55,4.60,5.00
378,NaN,25,23/05/2026,20:00,Valencia,Barcelona,3,1,H,0,...,1.87,3.40,4.10,1.93,3.40,4.0,1.95,3.30,4.00,1.95
379,NaN,25,24/05/2026,20:00,Villarreal,Ath Madrid,5,1,H,4,...,2.45,NaN,NaN,NaN,NaN,NaN,NaN,2.40,3.80,2.60